name: Main Pipeline

'on':
  push:
    branches: [main, develop, ci/TIRI-5-add-local-ci-and-git-hooks]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  run-reusable-ci:
    uses: yaaanni/iot-shared-actions/.github/workflows/java-ci.yml@66aa6be53619111d090972ac663fbeaa7debd585
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
