name: Main Pipeline

'on':
  push:
    branches: [main, develop, ci/TIRI-5-add-local-ci-and-git-hooks]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  run-reusable-ci:
    uses: yaaanni/iot-shared-actions/.github/workflows/java-ci.yml@fbf1825ffac2674e4ecb9cd20497ffc41de64e40
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
